name: analytics
description: Analytics implementation package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=3.10.0"

dependencies:
  firebase_analytics: ^11.4.1
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0 