name: arch_template
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  analytics:
    path: packages/analytics
  auth_repository:
    path: packages/auth_repository
  auto_route: ^9.3.0+1
  auto_route_generator: ^9.0.0
  bloc: ^9.0.0
  build_runner: ^2.4.6
  equatable: ^2.0.7
  firebase_analytics: ^11.4.1
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_crashlytics: ^4.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  get_it: ^8.0.3
  injectable: ^2.5.0
  injectable_generator: ^2.7.0
  intl: ^0.19.0
  upgrader: ^11.3.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  melos: ^6.3.2
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
