name: mason_template_generator
description: A CLI tool to convert Flutter projects into Mason bricks
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1

executables:
  mason_template_generator: mason_template_generator
