name: notifications
description: A package for notifications
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  capabilites:
    path: ../capabilites
  firebase_crashlytics: ^4.3.3
  firebase_messaging: ^15.2.3

  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
